// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: r5Q4Z1cxFkCcTJmiuBHM4s
// Component: yn3h3UAxym5Z

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: vUqIgiqOfSKO/component
import Button2 from "../../Button2"; // plasmic-import: L9J39x6OJe4i/component

import { useScreenVariants as useScreenVariants_4KrsLKoCkec } from "../blank_website_mobile_first/PlasmicGlobalVariant__Screen"; // plasmic-import: 4krsLKo_Ckec/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "../blank_website_mobile_first/plasmic.module.css"; // plasmic-import: r5Q4Z1cxFkCcTJmiuBHM4s/projectcss
import sty from "./PlasmicKueKering.module.css"; // plasmic-import: yn3h3UAxym5Z/css

import ArrowLeftSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__ArrowLeftSvgrepoCom1Svg"; // plasmic-import: UroXee_yw1o3/icon

createPlasmicElementProxy;

export type PlasmicKueKering__VariantMembers = {};
export type PlasmicKueKering__VariantsArgs = {};
type VariantPropType = keyof PlasmicKueKering__VariantsArgs;
export const PlasmicKueKering__VariantProps = new Array<VariantPropType>();

export type PlasmicKueKering__ArgsType = {};
type ArgPropType = keyof PlasmicKueKering__ArgsType;
export const PlasmicKueKering__ArgProps = new Array<ArgPropType>();

export type PlasmicKueKering__OverridesType = {
  root?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  link?: Flex__<"a"> & Partial<LinkProps>;
  img?: Flex__<typeof PlasmicImg__>;
  button2?: Flex__<typeof Button2>;
};

export interface DefaultKueKeringProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicKueKering__RenderFunc(props: {
  variants: PlasmicKueKering__VariantsArgs;
  args: PlasmicKueKering__ArgsType;
  overrides: PlasmicKueKering__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_4KrsLKoCkec()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <section className={classNames(projectcss.all, sty.section___2Bynz)}>
            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={`/menu`}
              platform={"nextjs"}
            >
              <ArrowLeftSvgrepoCom1SvgIcon
                className={classNames(projectcss.all, sty.svg__fi840)}
                role={"img"}
              />
            </PlasmicLink__>
          </section>
          <section className={classNames(projectcss.all, sty.section__l4O2G)}>
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "100%"
                  : "auto"
              }
              loading={"lazy"}
              src={{
                src: "/plasmic/bumar/images/_0475316001650443155Shutterstock1718969488Jpg.jpg",
                fullWidth: 1200,
                fullHeight: 675,
                aspectRatio: undefined
              }}
            />
          </section>
          <section className={classNames(projectcss.all, sty.section___0RuUf)}>
            <div className={classNames(projectcss.all, sty.freeBox__ujZvy)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vIjxm)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zyVl7)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__oVwLe)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__vx4WH)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__s5Gsx
                        )}
                      >
                        {"Harga paket kue kering"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rc3Us
                      )}
                    >
                      {"Minimal pemesanan produk 3, 6 produk"}
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__zmDt6)}>
            <div className={classNames(projectcss.all, sty.columns___7RUcJ)}>
              <div className={classNames(projectcss.all, sty.column__rie6L)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d0NN
                  )}
                >
                  {"Kue Nastar"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__uLkVn)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iZtM6
                  )}
                >
                  {"Rp.90.000"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__np9LT)}>
              <div className={classNames(projectcss.all, sty.column__xk4T)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gG66J
                  )}
                >
                  {"Kue Sagu keju"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__gcJ)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__n63Jk
                  )}
                >
                  {"Rp.90.000"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__x0ZAy)}>
              <div className={classNames(projectcss.all, sty.column__a7Nc1)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yvrw7
                  )}
                >
                  {"kue Lidah kucing"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__dG1Ub)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lITa
                  )}
                >
                  {"Rp.90.000"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__hd1SU)}>
              <div className={classNames(projectcss.all, sty.column__zXvGh)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cksPj
                  )}
                >
                  {"Kue putri salju"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__dgV9N)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ne0T
                  )}
                >
                  {"Rp.90.000"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__dIdI)}>
              <div className={classNames(projectcss.all, sty.column__wHd2R)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cj32Q
                  )}
                >
                  {"Kue kastengel keju"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__nwOfH)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mC9Pm
                  )}
                >
                  {"Rp.120.000"}
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.columns__wOeBp)}>
              <div className={classNames(projectcss.all, sty.column__rKfz)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__t40N4
                  )}
                >
                  {"Kue kacang"}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__cyAf)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__zhrpl
                  )}
                >
                  {"Rp. 85.000"}
                </div>
              </div>
            </div>
            <section
              className={classNames(projectcss.all, sty.section___06XsF)}
            >
              <Button2
                data-plasmic-name={"button2"}
                data-plasmic-override={overrides.button2}
                className={classNames("__wab_instance", sty.button2)}
                endIcon={
                  <svg
                    className={classNames(projectcss.all, sty.svg__fdLF)}
                    role={"img"}
                  />
                }
                startIcon={
                  <svg
                    className={classNames(projectcss.all, sty.svg__s9Lyr)}
                    role={"img"}
                  />
                }
                submitsForm={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cUKcu
                  )}
                >
                  {"Booking now ->"}
                </div>
              </Button2>
            </section>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navbar", "link", "img", "button2"],
  navbar: ["navbar"],
  link: ["link"],
  img: ["img"],
  button2: ["button2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  link: "a";
  img: typeof PlasmicImg__;
  button2: typeof Button2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicKueKering__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicKueKering__VariantsArgs;
    args?: PlasmicKueKering__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicKueKering__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicKueKering__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicKueKering__ArgProps,
          internalVariantPropNames: PlasmicKueKering__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicKueKering__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicKueKering";
  } else {
    func.displayName = `PlasmicKueKering.${nodeName}`;
  }
  return func;
}

export const PlasmicKueKering = Object.assign(
  // Top-level PlasmicKueKering renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    link: makeNodeComponent("link"),
    img: makeNodeComponent("img"),
    button2: makeNodeComponent("button2"),

    // Metadata about props expected for PlasmicKueKering
    internalVariantProps: PlasmicKueKering__VariantProps,
    internalArgProps: PlasmicKueKering__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicKueKering;
/* prettier-ignore-end */
