// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: r5Q4Z1cxFkCcTJmiuBHM4s
// Component: k811IsW6KBen

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: vUqIgiqOfSKO/component
import Button2 from "../../Button2"; // plasmic-import: L9J39x6OJe4i/component

import { useScreenVariants as useScreenVariants_4KrsLKoCkec } from "../blank_website_mobile_first/PlasmicGlobalVariant__Screen"; // plasmic-import: 4krsLKo_Ckec/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "../blank_website_mobile_first/plasmic.module.css"; // plasmic-import: r5Q4Z1cxFkCcTJmiuBHM4s/projectcss
import sty from "./PlasmicHampers.module.css"; // plasmic-import: k811IsW6KBen/css

import ArrowLeftSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__ArrowLeftSvgrepoCom1Svg"; // plasmic-import: UroXee_yw1o3/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 9OcZEOS6XKco/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: f30sqqHn8JbB/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: rx8PB0YDgyof/icon

createPlasmicElementProxy;

export type PlasmicHampers__VariantMembers = {};
export type PlasmicHampers__VariantsArgs = {};
type VariantPropType = keyof PlasmicHampers__VariantsArgs;
export const PlasmicHampers__VariantProps = new Array<VariantPropType>();

export type PlasmicHampers__ArgsType = {};
type ArgPropType = keyof PlasmicHampers__ArgsType;
export const PlasmicHampers__ArgProps = new Array<ArgPropType>();

export type PlasmicHampers__OverridesType = {
  root?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  link?: Flex__<"a"> & Partial<LinkProps>;
  img?: Flex__<typeof PlasmicImg__>;
  columns?: Flex__<"div">;
  column?: Flex__<"div">;
};

export interface DefaultHampersProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHampers__RenderFunc(props: {
  variants: PlasmicHampers__VariantsArgs;
  args: PlasmicHampers__ArgsType;
  overrides: PlasmicHampers__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_4KrsLKoCkec()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <section className={classNames(projectcss.all, sty.section__aZy44)}>
            <PlasmicLink__
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(projectcss.all, projectcss.a, sty.link)}
              component={Link}
              href={`/menu`}
              platform={"nextjs"}
            >
              <ArrowLeftSvgrepoCom1SvgIcon
                className={classNames(projectcss.all, sty.svg__qdEex)}
                role={"img"}
              />
            </PlasmicLink__>
          </section>
          <section className={classNames(projectcss.all, sty.section__mrxz9)}>
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={
                hasVariant(globalVariants, "screen", "desktopOnly")
                  ? "100%"
                  : "auto"
              }
              loading={"lazy"}
              src={{
                src: "/plasmic/bumar/images/_0475316001650443155Shutterstock1718969488Jpg.jpg",
                fullWidth: 1200,
                fullHeight: 675,
                aspectRatio: undefined
              }}
            />
          </section>
          <section className={classNames(projectcss.all, sty.section__wiHgS)}>
            <div className={classNames(projectcss.all, sty.freeBox___2N5Sx)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__brTiq)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__a1GsU)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__gTaw7)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ytuGv)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__clRrv
                        )}
                      >
                        {"Harga paket Hampers"}
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w6Ke5
                      )}
                    >
                      {"Paket kue kering parcel "}
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </section>
          <Stack__
            as={"div"}
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns)}
          >
            <div
              data-plasmic-name={"column"}
              data-plasmic-override={overrides.column}
              className={classNames(projectcss.all, sty.column)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__wduor)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__lhbOa)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__chmWj)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5VgGx
                      )}
                    >
                      {"Paket 3 box"}
                    </div>
                  </Stack__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wqU5V
                    )}
                  >
                    {"Rp. 47.000"}
                  </div>
                  <Button2
                    className={classNames(
                      "__wab_instance",
                      sty.button2___2Xnny
                    )}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__gGyPl)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__gmsGz)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xPrk
                      )}
                    >
                      {"Booking"}
                    </div>
                  </Button2>
                </Stack__>
                <div
                  className={classNames(projectcss.all, sty.freeBox___8ZfhE)}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zWs2)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nZWd)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aCpP8)}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__uXtz1)}
                        role={"img"}
                      />
                    </div>
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bQjZ
                        )}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__zQg2F)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__jNxGu)}
                    >
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iDGyY
                          )}
                        >
                          {"Label"}
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zz2NA
                        )}
                      >
                        {"Nastar"}
                      </div>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dSp)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__oZeo5)}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__eRmnx)}
                        role={"img"}
                      />
                    </div>
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__o99Il
                        )}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__x0NpY)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__o9AjI)}
                    >
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bopBg
                          )}
                        >
                          {"Label"}
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jl0A
                        )}
                      >
                        {"Lidah kucing"}
                      </div>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__x2RHs)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___8NPdp
                      )}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___9EwUg)}
                        role={"img"}
                      />
                    </div>
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xWFzs
                        )}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__mpG7Q)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__cvQ5U)}
                    >
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eLfF
                          )}
                        >
                          {"Label"}
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4QPcg
                        )}
                      >
                        {"Kastangel"}
                      </div>
                    </Stack__>
                  </Stack__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__inh7)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___2BZgj)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ldXjv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3THk
                      )}
                    >
                      {"Paket 6 box"}
                    </div>
                  </Stack__>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gsZih
                    )}
                  >
                    {"Rp. 47.000"}
                  </div>
                  <Button2
                    className={classNames("__wab_instance", sty.button2__a4Txd)}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__pbCix)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <ChecksvgIcon
                        className={classNames(projectcss.all, sty.svg__bVurX)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1ESrv
                      )}
                    >
                      {"Booking"}
                    </div>
                  </Button2>
                </Stack__>
                <div
                  className={classNames(projectcss.all, sty.freeBox__d94Us)}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dmE7I)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ritPw)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lauZ3)}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__qEtPi)}
                        role={"img"}
                      />
                    </div>
                    {false ? (
                      <div
                        className={classNames(projectcss.all, sty.freeBox__shO)}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__forl3)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__kz7Wt)}
                    >
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jzsyh
                          )}
                        >
                          {"Label"}
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6EVX
                        )}
                      >
                        {"Nastar"}
                      </div>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rdy2P)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yu8H5)}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__alfX0)}
                        role={"img"}
                      />
                    </div>
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__a597R
                        )}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__yWqKl)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__tIsWu)}
                    >
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wjDSw
                          )}
                        >
                          {"Label"}
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ig7FO
                        )}
                      >
                        {"Putri salju"}
                      </div>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__oQmG9)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__e1LA)}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__hMqO)}
                        role={"img"}
                      />
                    </div>
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___1K6W0
                        )}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__hi49U)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox___7GGC)}
                    >
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wS5Ii
                          )}
                        >
                          {"Label"}
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sSli8
                        )}
                      >
                        {"Kastangel "}
                      </div>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__r2Sav)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kx0DK)}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__psZjf)}
                        role={"img"}
                      />
                    </div>
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xgrYv
                        )}
                      >
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___1EgXr
                          )}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___2LxPf
                      )}
                    >
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ugGnq
                          )}
                        >
                          {"Label"}
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2XRr2
                        )}
                      >
                        {"Kue kacang"}
                      </div>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vnNp3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__h2EvS)}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__nO91)}
                        role={"img"}
                      />
                    </div>
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___6OV2
                        )}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__pgz6N)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__r8VT7)}
                    >
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qDiDp
                          )}
                        >
                          {"Label"}
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vwOga
                        )}
                      >
                        {"Sagu keju"}
                      </div>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__uC1W2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rrOn3)}
                    >
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___0SaNb)}
                        role={"img"}
                      />
                    </div>
                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__t4Q5C
                        )}
                      >
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__nl2Nb)}
                          role={"img"}
                        />
                      </div>
                    ) : null}
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__hNlgr)}
                    >
                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__o4CB
                          )}
                        >
                          {"Label"}
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aOkFc
                        )}
                      >
                        {"Lidah kucing"}
                      </div>
                    </Stack__>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navbar", "link", "img", "columns", "column"],
  navbar: ["navbar"],
  link: ["link"],
  img: ["img"],
  columns: ["columns", "column"],
  column: ["column"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  link: "a";
  img: typeof PlasmicImg__;
  columns: "div";
  column: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHampers__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHampers__VariantsArgs;
    args?: PlasmicHampers__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHampers__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHampers__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHampers__ArgProps,
          internalVariantPropNames: PlasmicHampers__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHampers__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHampers";
  } else {
    func.displayName = `PlasmicHampers.${nodeName}`;
  }
  return func;
}

export const PlasmicHampers = Object.assign(
  // Top-level PlasmicHampers renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    link: makeNodeComponent("link"),
    img: makeNodeComponent("img"),
    columns: makeNodeComponent("columns"),
    column: makeNodeComponent("column"),

    // Metadata about props expected for PlasmicHampers
    internalVariantProps: PlasmicHampers__VariantProps,
    internalArgProps: PlasmicHampers__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHampers;
/* prettier-ignore-end */
