// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: r5Q4Z1cxFkCcTJmiuBHM4s
// Component: cTtvcxMxKXL7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: vUqIgiqOfSKO/component
import Button2 from "../../Button2"; // plasmic-import: L9J39x6OJe4i/component
import { SliderWrapper } from "@plasmicpkgs/react-slick";
import { sliderHelpers as SliderWrapper_Helpers } from "@plasmicpkgs/react-slick";
import Footer from "../../Footer"; // plasmic-import: ioaSz0ukZyBm/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariants_4KrsLKoCkec } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 4krsLKo_Ckec/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: r5Q4Z1cxFkCcTJmiuBHM4s/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: cTtvcxMxKXL7/css

import Banner1SvgIcon from "../bumar/icons/PlasmicIcon__Banner1Svg"; // plasmic-import: -QJg3kyDQ7GD/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  banner?: Flex__<"svg">;
  button2?: Flex__<typeof Button2>;
  sliderCarousel?: Flex__<typeof SliderWrapper>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "sliderCarousel.currentSlide",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 0,

        refName: "sliderCarousel",
        onMutate: generateOnMutateForSpec("currentSlide", SliderWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_4KrsLKoCkec()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <Navbar className={classNames("__wab_instance", sty.navbar__qNpv4)} />

          <section className={classNames(projectcss.all, sty.section__u9A)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__lf0JI)}
            >
              <Banner1SvgIcon
                data-plasmic-name={"banner"}
                data-plasmic-override={overrides.banner}
                className={classNames(projectcss.all, sty.banner)}
                role={"img"}
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6Ssyj)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__a3U5Y
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#000000" }}
                    >
                      {"Catering Bumar"}
                    </span>
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___9VlXl
                  )}
                >
                  {
                    "Salah satu perusahaan jasa katering dan Kami menerima order Nasi box / Kue kering / Snack box / hampers, untuk segala keperluan acara anda. disini anda bisa memesan beragam nasi box dengan menu utama kami."
                  }
                </div>
                <Button2
                  data-plasmic-name={"button2"}
                  data-plasmic-override={overrides.button2}
                  className={classNames("__wab_instance", sty.button2)}
                  endIcon={
                    <svg
                      className={classNames(projectcss.all, sty.svg__tMfom)}
                      role={"img"}
                    />
                  }
                  startIcon={
                    <svg
                      className={classNames(projectcss.all, sty.svg__qs41H)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__btAud
                    )}
                  >
                    {"Booking now ->"}
                  </div>
                </Button2>
              </Stack__>
            </Stack__>
            {(() => {
              const child$Props = {
                arrows: false,
                autoplay: true,
                autoplaySpeed: 0,
                beforeChange: generateStateOnChangePropForCodeComponents(
                  $state,
                  "currentSlide",
                  ["sliderCarousel", "currentSlide"],
                  SliderWrapper_Helpers
                ),
                centerMode: true,
                className: classNames("__wab_instance", sty.sliderCarousel),
                cssEase: "linear",
                initialSlide: generateStateValueProp($state, [
                  "sliderCarousel",
                  "currentSlide"
                ]),
                ref: ref => {
                  $refs["sliderCarousel"] = ref;
                },
                sliderScopeClassName: sty["sliderCarousel__slider"],
                speed: 5000
              };
              initializeCodeComponentStates(
                $state,
                [
                  {
                    name: "currentSlide",
                    plasmicStateName: "sliderCarousel.currentSlide"
                  }
                ],
                [],
                SliderWrapper_Helpers ?? {},
                child$Props
              );

              return (
                <SliderWrapper
                  data-plasmic-name={"sliderCarousel"}
                  data-plasmic-override={overrides.sliderCarousel}
                  {...child$Props}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ilM1S)}
                  >
                    <section
                      className={classNames(projectcss.all, sty.section__dFgZc)}
                    >
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__dydRv
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__gpS29)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "desktopOnly")
                              ? "822px"
                              : "100%"
                          }
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/bumar/images/_1650607449326RekomendasiHampersLebaranTerbaikDenganHargaTerjangkaujpg.jpg",
                            fullWidth: 762,
                            fullHeight: 706,
                            aspectRatio: undefined
                          }}
                        />
                      </section>
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__dGoNo
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rqBom
                          )}
                        >
                          {"Hampers"}
                        </div>
                      </section>
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__wr3G
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sKmNg
                          )}
                        >
                          {
                            "Dengan kemasan eksklusif dari bumar,  Kami menawarkan berbagai produk mulai dari kue kering dan oleh-oleh premium, hingga hadiah."
                          }
                        </div>
                      </section>
                    </section>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ko5B8)}
                  >
                    <section
                      className={classNames(projectcss.all, sty.section__nxEjW)}
                    >
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__ecXub
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__nig)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "desktopOnly")
                              ? "822px"
                              : "100%"
                          }
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/bumar/images/_1650607449326RekomendasiHampersLebaranTerbaikDenganHargaTerjangkaujpg.jpg",
                            fullWidth: 762,
                            fullHeight: 706,
                            aspectRatio: undefined
                          }}
                        />
                      </section>
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__evC2I
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__x8I9B
                          )}
                        >
                          {"Nasi box"}
                        </div>
                      </section>
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__s6IfS
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qJihe
                          )}
                        >
                          {
                            "Dengan kemasan eksklusif dari bumar,  Kami menawarkan berbagai produk mulai dari kue kering dan oleh-oleh premium, hingga hadiah."
                          }
                        </div>
                      </section>
                    </section>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ckcfo)}
                  >
                    <section
                      className={classNames(projectcss.all, sty.section__vz9Cn)}
                    >
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__qXRk
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__fmcJj)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "desktopOnly")
                              ? "822px"
                              : "100%"
                          }
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/bumar/images/_1650607449326RekomendasiHampersLebaranTerbaikDenganHargaTerjangkaujpg.jpg",
                            fullWidth: 762,
                            fullHeight: 706,
                            aspectRatio: undefined
                          }}
                        />
                      </section>
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section___6Am1
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pQw0S
                          )}
                        >
                          {"Nasi box"}
                        </div>
                      </section>
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__wNGyy
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__s23No
                          )}
                        >
                          {
                            "Dengan kemasan eksklusif dari bumar,  Kami menawarkan berbagai produk mulai dari kue kering dan oleh-oleh premium, hingga hadiah."
                          }
                        </div>
                      </section>
                    </section>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__srlox)}
                  >
                    <section
                      className={classNames(projectcss.all, sty.section__rw7)}
                    >
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__q9ImD
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__jzHj)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={
                            hasVariant(globalVariants, "screen", "desktopOnly")
                              ? "822px"
                              : "100%"
                          }
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/bumar/images/_1650607449326RekomendasiHampersLebaranTerbaikDenganHargaTerjangkaujpg.jpg",
                            fullWidth: 762,
                            fullHeight: 706,
                            aspectRatio: undefined
                          }}
                        />
                      </section>
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__i2Ixr
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xUmf
                          )}
                        >
                          {"Nasi box"}
                        </div>
                      </section>
                      <section
                        className={classNames(
                          projectcss.all,
                          sty.section__onkfy
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___1OgvM
                          )}
                        >
                          {
                            "Dengan kemasan eksklusif dari bumar,  Kami menawarkan berbagai produk mulai dari kue kering dan oleh-oleh premium, hingga hadiah."
                          }
                        </div>
                      </section>
                    </section>
                  </div>
                </SliderWrapper>
              );
            })()}
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />

          {(
            hasVariant(globalVariants, "screen", "desktopOnly") ? true : false
          ) ? (
            <Navbar
              className={classNames("__wab_instance", sty.navbar___09PVy)}
            />
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "banner", "button2", "sliderCarousel", "footer"],
  banner: ["banner"],
  button2: ["button2"],
  sliderCarousel: ["sliderCarousel"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  banner: "svg";
  button2: typeof Button2;
  sliderCarousel: typeof SliderWrapper;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    banner: makeNodeComponent("banner"),
    button2: makeNodeComponent("button2"),
    sliderCarousel: makeNodeComponent("sliderCarousel"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
